service: prvni-serverless-aplikace

plugins:
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: moje-lambda
          method: POST
